version: '3.4'

services:
  northwind.ui:
    image: ${DOCKER_REGISTRY-}northwindui
    build:
      context: .
      dockerfile: Northwind.UI/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Admin123*
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"