version: '3.4'

services:
  northwind.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      #- "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro